### ISSUE TITLE
Error for Forget20-KP_35_3_1-10_2box_10_10

### ISSUE THREAD

**Issue by relund** [MCDMSociety/MOrepo-Forget20#8]
This instance have to be checked. The different alg config gives different results. 

```
1 1525    Forget2~ KP       35     3 2box         1       10 depth   mof    None       1   141
2 1526    Forget2~ KP       35     3 2box         1       10 breadth mof    None       1   141
3 1527    Forget2~ KP       35     3 2box         1       10 depth   mfavg  None       1   141
4 1528    Forget2~ KP       35     3 2box         1       10 breadth mfavg  None       1   140
```
The `UB` file has 140 non-dominated points.

**Comment by relund** [comment]
The same holds for `Forget20-KP_40_3_1-10_random_6_6`, `Forget20-AP_10_3_1-10_2box_1_4`

**Comment by NicolasJForget** [comment]
The new Knapsack instances & results are coming, but I will do re-check before uploading anything, to make sure that we do not end up with more of these problems.

This kind of non-consistent results may come from the fact that the instance is solved in one configuration but not in another. You may check the feature "solved" (= 1 if solved, 0 otherwise) from stat.csv for this purpose. Given the instances parameters, I think it may be the case for the AP instance, but not for the KP instances. In this case, I think that it comes from my error parameter in my algorithm again.
